<a href="https://colab.research.google.com/github/DiegoVianaR/Case-Study-OrchidLog/blob/main/Case_Study_OrchidLog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Etapa 1:
#Ingestão e Leitura dos Dados

#importar a biblioteca Pandas
import pandas as pd

#criar as variaveis de acordo com as planilhas
dados_logistica = "/content/entregas_orquideas.csv"
dados_agricolas = "/content/estufas_qualidade.csv"
dados_telemetria = "/content/telemetria_iot.csv"

#Criar os dataframe de acordo com as variaveis
df_dados_logistica = pd.read_csv(dados_logistica)
df_dados_agricolas = pd.read_csv(dados_agricolas)
df_dados_telemetria = pd.read_csv(dados_telemetria)

#Exibição das planilhas
display(df_dados_logistica.head(1000))
display(df_dados_agricolas.head(1000))
display(df_dados_telemetria.head(1000))

,ID_Carga,Placa_Caminhao,Estufa_Origem,UF_Destino,Qtd_Orquideas,Status_Entrega
0,LOG-1000,TX-103,EST-3,SP,457,Entregue
1,LOG-1001,TX-100,EST-1,SC,165,Entregue
2,LOG-1002,TX-108,EST-2,MG,124,Entregue
3,LOG-1003,TX-107,EST-1,RJ,162,Entregue
4,LOG-1004,TX-107,EST-2,SP,469,Entregue
...,...,...,...,...,...,...
195,LOG-1195,TX-114,EST-2,SP,278,Entregue
196,LOG-1196,TX-107,EST-2,MG,166,Entregue
197,LOG-1197,TX-102,EST-2,PR,367,Cancelado
198,LOG-1198,TX-114,EST-3,PR,328,Atrasado
199,LOG-1199,TX-103,EST-3,PR,176,Entregue

,id_estufa,especie_predominante,umidade_media_pct,responsavel_tecnico,indice_qualidade_lote
0,EST-1,Phalaenopsis,75,Ana Silva,0.95
1,EST-2,Cattleya,82,Carlos Mendes,0.88
2,EST-3,Dendrobium,65,Mariana Costa,0.91

   Placa_Caminhao  Temperatura_C Alerta_Calor
0          TX-103             20          NAO
1          TX-100             30          SIM
2          TX-108             28          SIM
3          TX-107             33          SIM
4          TX-104             20          NAO
5          TX-102             21          NAO
6          TX-113             34          SIM
7          TX-101             32          SIM
8          TX-106             33          SIM
9          TX-114             23          NAO
10         TX-105             22          NAO
11         TX-110             26          NAO
12         TX-112             27          NAO
13         TX-111             27          NAO
14         TX-109             23          NAO
15         TX-115             33          SIM

In [29]:
#Etapa 2: Classificação com Estruturas de Repetição
# Monitoramento de temperatura

#Criação de lista para verificar temperatura
list_status_temperatura = []

list_temp = df_dados_telemetria["Temperatura_C"]. tolist()

#Criar loop com for, para conferir a coluna "dados temperadura"
for t in list_temp:
  #Criar parametro para mostrar mensagem de ALERTA ou OK, de acordo com a temperatura exibida
  if t >=28:
    list_status_temperatura.append("ALERTA")

  else:
    list_status_temperatura.append("OK")

#Exibir nova coluna com a informação do if e else (ALERTA ou OK)
df_dados_telemetria["dados_temperatura"] = list_status_temperatura

display(df_dados_telemetria)

   Placa_Caminhao  Temperatura_C Alerta_Calor dados_temperatura
0          TX-103             20          NAO                OK
1          TX-100             30          SIM            ALERTA
2          TX-108             28          SIM            ALERTA
3          TX-107             33          SIM            ALERTA
4          TX-104             20          NAO                OK
5          TX-102             21          NAO                OK
6          TX-113             34          SIM            ALERTA
7          TX-101             32          SIM            ALERTA
8          TX-106             33          SIM            ALERTA
9          TX-114             23          NAO                OK
10         TX-105             22          NAO                OK
11         TX-110             26          NAO                OK
12         TX-112             27          NAO                OK
13         TX-111             27          NAO                OK
14         TX-109             23          NAO                OK
15         TX-115             33          SIM            ALERTA

In [31]:
#Etapa 3: Estatística Básica e Diagnóstico
#01 - Quantidade total de orquídeas transportadas

df_diagnostico_geral = df_dados_logistica

display(df_diagnostico_geral)

print(f"A quantidade total de orquídeas transportadas é: {df_diagnostico_geral["Qtd_Orquideas"].sum()}")

print(f"A quantidade total de orquídeas perdidas: {df_diagnostico_geral["Qtd_Orquideas"].sum()}")

,ID_Carga,Placa_Caminhao,Estufa_Origem,UF_Destino,Qtd_Orquideas,Status_Entrega
0,LOG-1000,TX-103,EST-3,SP,457,Entregue
1,LOG-1001,TX-100,EST-1,SC,165,Entregue
2,LOG-1002,TX-108,EST-2,MG,124,Entregue
3,LOG-1003,TX-107,EST-1,RJ,162,Entregue
4,LOG-1004,TX-107,EST-2,SP,469,Entregue
...,...,...,...,...,...,...
195,LOG-1195,TX-114,EST-2,SP,278,Entregue
196,LOG-1196,TX-107,EST-2,MG,166,Entregue
197,LOG-1197,TX-102,EST-2,PR,367,Cancelado
198,LOG-1198,TX-114,EST-3,PR,328,Atrasado
199,LOG-1199,TX-103,EST-3,PR,176,Entregue

A quantidade total de orquídeas transportadas é: 55425
A quantidade total de orquídeas perdidas: 55425

In [30]:
#02 - Quantidade total de orquídeas perdidas no transporte

df_perdas = df_dados_logistica[df_dados_logistica["Status_Entrega"] == "Cancelado"]

print(f"A quantidade total de orquídeas perdidas: {df_perdas["Qtd_Orquideas"].sum()}")

A quantidade total de orquídeas perdidas: 6349

In [36]:
#03 - Impacto Regional, estado que vai sofreu com cancelamentos de entrega

df_estados = df_dados_logistica[df_dados_logistica["Status_Entrega"] == "Cancelado"]

print(f"O estado que mais sofreu com os cancelamentos:{df_estados["UF_Destino"].mode()}")

O estado que mais sofreu com os cancelamentos:0    SP
Name: UF_Destino, dtype: object

In [41]:
#04 - Qual foi a temperatura máxima e a temperatura média?
df_max_temperatura = df_dados_telemetria

print(f" A temperatura máxima foi: {df_max_temperatura["Temperatura_C"].max()}")

print(f" A temperatura média foi: {df_max_temperatura["Temperatura_C"].median()}")

 A temperatura máxima foi: 34
 A temperatura média foi: 27.0